version: "3.5"
services:
  php_fpm:
    build: .
    container_name: docker_example_fpm
    working_dir: /usr/share/nginx/docker_example
    networks:
      - test_network
    depends_on:
      - composer
    volumes:
      - ./:/usr/share/nginx/docker_example
  nginx:
    image: nginx:latest
    container_name: docker_example_nginx
    working_dir: /usr/share/nginx/docker_example
    networks:
      - test_network
    ports:
      - "8888:80"
    links:
      - php_fpm
      - composer
    volumes:
      - ./:/usr/share/nginx/docker_example
      - ./default.conf:/etc/nginx/conf.d/default.conf
  composer:
    image: composer:latest
    container_name: docker_example_composer
    working_dir: /usr/share/nginx/docker_example
    networks:
      - test_network
    command: install
    volumes:
      - .:/usr/share/nginx/docker_example
networks:
  test_network:
